---
 - name: check cpu information
   hosts: all
   become: yes

   tasks:
     - name: get cpu information
       ansible.builtin.command: nproc
       register: cpu_result

     - name: display cpu information
       ansible.builtin.debug:
         msg: "the cpu information is {{cpu_result.stdout}}"


