---
 - name: check server diskspace
   hosts: all
   become: yes


   tasks:
    - name: get diskspace
      ansible.builtin.command: df -h
      register: disk_result

    - name: display diskspace
      ansible.builtin.debug:
        msg: " the diskspace is {{disk_result.stdout}}"

