---
 - name: check server hostname
   hosts: all
   become: yes

   
   tasks: 
    - name: get hostname
      ansible.builtin.command: hostname
      register: hostname_result

    - name: display hostname
      ansible.builtin.debug:
        msg: " the hostname is {{hostname_result.stdout}}"

