---
 - name: check server uptime
   hosts: all
   become: yes


   tasks:
    - name: get server uptime
      ansible.builtin.command: uptime
      register: uptime_result

    - name: display uptime
      ansible.builtin.debug:
        msg: " the serveruptime is {{uptime_result.stdout}}"

